config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'pages/about', to: 'pages#about'
  get 'pages/contact', to: 'pages#contact'
  # get 'pages/blog', to: 'pages#blog'
  get 'pages/blog', to: 'pages#index'
  get 'pages/projects', to: 'pages#projects'
  get 'pages/ldnsouth', to: 'pages#ldnsouth'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'blog', to: 'pages#blog'
  get 'projects', to: 'pages#projects'
  get 'ldnsouth', to: 'pages#ldnsouth'

  # get 'blog', to: 'pages#index'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true
end

app/models/message.rb
# We dont want to inherit from ApplicationRecord
# class Message < ApplicationRecord
# end

class Message
    include ActiveModel::Model
    attr_accessor :name, :email, :body
    validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    # once blog complete apply the following
    # skip_before_action :authenticate_user!, only: %i[show index ]
    # before_action :set_article, only: %i[edit update show destroy]
    skip_before_action :authenticate_user!, only: %i[new create index edit update show destroy]
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    # commented out line below on 31/12/18
    # before_action :set_article, only: %i[destroy]

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
         flash[:notice] = "Article was updated"
         redirect_to article_path(@article)
        else
         flash[:notice] = "Article was not updated"
         render 'edit'
        end
    end

    def index
        @articles = Article.all
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
    end

    private
    def article_params
        params.require(:article).permit(:title, :description)
    end

    def set_article
        @article = Article.find(params[:id])
       end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  skip_before_action :authenticate_user!, only: %i[home blog about contact index projects ldnsouth]

  def index
  end
  
  def home
  end

  def about
  end

  def contact
  end

  def blog
  end

  def projects
  end

  def ldnsouth
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # def markdown(description)
    #     renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    #     options = {
    #         autolink: true,
    #         no_intra_emphasis: true,
    #         disable_indented_code_blocks: true,
    #         fenced_code_blocks: true,
    #         lax_html_blocks: true,
    #         strikethrough: true,
    #         superscript: true,
    #         tables: true,
    #         underline: true,
    #         highlight: true,
    #         quote: true,
    #         footnotes: true
    #     }
    #     Redcarpet::Markdown.new(renderer, options).render(description).html_safe
    # end
    class HTMLwithPygments < Redcarpet::Render::HTML
  
      def block_code(code, language)
        Pygments.highlight(code, lexer: language)
      end
  
    end
    def markdown(description)
      renderer = HTMLwithPygments.new(hard_wrap: true)
      options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        tables: true,
        underline: true,
        highlight: true,
        quote: true,
        footnotes: true
      }
      Redcarpet::Markdown.new(renderer, options).render(description).html_safe
    end
  end
  

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<%= render 'shared/form' %>

app/views/articles/index.html.erb
<div class="container">
    <div class="card-standard__white text-center__simple">
    <div class="text-normal__grey--verylarge">
    <p>Latest Articles<p>
    
        <% @articles.each do |article| %>
        <div class="text-normal__greyand31px">
        <%=  article.title %>
        </div>

        <!--
        <h4 class="description-blog"> </h4>
        <%=   article.description.truncate_words(4) %>
        <h4 class="description-blog red"> </h4>
        -->
        
        <div class="button-spacing_likeblog">
            <%= link_to 'Read more.', article_path(article), class: "btn btn-xs btn-success" %>
        </div>
         
        <% end %>
    
    <% if current_user && current_user.email=="erikap02@gmail.com" %>
        <div class="newarticle-blog">
        <%= link_to 'New Article', new_article_path(@article), class: "btn btn-xs btn-primary" %>
        </div>
    <% end %>
    

    </div>

    </div>
</div>

app/views/articles/new.html.erb
<%= render 'shared/form' %>

app/views/articles/show.html.erb
<!-- Old code above just left there, remove at the end
    -->


<div class ="background-white">
    <div class="container-bloglikemonbiot"> 
    <p class="blog-title__foreachtitle_likemonbiot"><%= @article.title %></p>
    <p><%= @article.created_at.strftime("%d %B %Y")  %> by Haseeb Chaudhary</p>
    <p><%= markdown @article.description %></p>
    <br>
    <br>
    <!-- This is basically saying if you're logged in and you are user Haseeb you can edit stuff 
    the && used to guard against nil errors 
    -->

    <!-- Here I've taken out the condition on who needs to be logged in
    -->

    
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
        
        <%= link_to 'Delete', article_path(@article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Are you sure?"} %> |
        
    <%= link_to 'Back', articles_path, class: "btn btn-xs btn-success" %>
    <br>
    <br>
        <div class="comments-blog">
            <p>Comments:</p>
        </div>
        <!-- Add the comments section later
       taken out all the article comments code from here, need to add it later
        -->

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Haseeb Chaudhary</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar-simple' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>

<% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>


</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        

          <!-- Google result text-->
        <title>Haseeb Chaudhary creative developer</title>
        <!-- Google result description-->
        <meta name="description" content="I build Web Applications, creatively">

        <!--<meta property="og:title" content="Le Wagon - The French innovative coding school">
        <meta property="og:image" content="facebook-card.jpg">
        <meta property="og:description" content="Le Wagon is the best French coding school for entrepreneurs. Checkout by yourself the projects of our students. You will be impressed.">
        <meta property="og:site_name" content="Le Wagon"/>-->
        
        <!-- Google fonts -->
        <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

        <!-- Fontawesome -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    </head>

    <div class="container">
        <div class="card-standard__white text-center__simple">
            
                <div class="text-normal__grey--verylarge">
                <p>Haseeb Chaudhary</p>
                </div>


                <br>
                <br>

                
                <table class="text-standard__size--15px">
                    <tbody>
                        <tr>
                            <td class="text-center_middleandcentre">
                                <div class="text-normal__greyand31px">
                                    <p>Full-Stack Developer</p>
                                </div>
                                <div class="text-normal__greyandmedium18px">                            
                                    <p> My story...I started life as a cyber security engineer and then learnt to code.  
                                    </p>
                                    <p> I like to develop web applications, mostly using Ruby on Rails and JavaScript. Full Stack Development is my thing.
                                    </p>
                                    <p> Mostly I'm based in Barcelona with my family but work stuff often means I'm scattered around Europe.
                                    </p>
                                </div>
                            </td>
                            <td>                          
                                <div class="card-overlay__standard">
                                    <%= image_tag("cool_pic.jpg", class: "object-fit_cover") %>
                                    <div class="overlay-text">
                                        <h1>"I often travel to gain inspiration from architecture, the magic of geometric design and the natural world."</h1>
                                        <p>Mixing deep tech and creative design is a live long journey. Don't be shy about getting intouch.</p>
                                            <div class="team-title">Haseeb Chaudhary - Inspired Design
                                            </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>

                

            
        </div>
    </div>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
          <!-- Google result text-->
        <title>Erika Chaudhary creative writer</title>
        <!-- Google result description-->
        <meta name="description" content="I write about personal experiences within a humanist and global context">

        <!--<meta property="og:title" content="Le Wagon - The French innovative coding school">
        <meta property="og:image" content="facebook-card.jpg">
        <meta property="og:description" content="Le Wagon is the best French coding school for entrepreneurs. Checkout by yourself the projects of our students. You will be impressed.">
        <meta property="og:site_name" content="Le Wagon"/>-->

     

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    </head>

<body>
  <div class="homepage-hero-module">
    <div class="video-container">
      <div class="filter"></div>
      <video autoplay loop muted playsinline class="fillWidth">
        <source src="videos/Writing-Working.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
        <source src="videos/Writing-Working.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
      </video>
      <div class="poster hidden">
        <img src="Writing-Working.jpg" alt="">
      </div>
    </div>

  </div>

<!-- Below is the contact form I built which could be used -->
<!-- <%#=  render 'shared/contact-form-minimal' %> -->




<!-- .wrapper
  .scroll-list
    .scroll-list__wrp.js-scroll-content.js-scroll-list
      - for (i = 0; i <= 25; i++)
        .scroll-list__item.js-scroll-list-item -->




<div class="text-normal__grey text-center__simple padding-aroundtext__medium">

<form action="https://formspree.io/haseebchaudhary@gmail.com" method="POST" id="form1">


           
            <p class="text-normal__greyand31px"> Don't be shy about getting intouch </p> <br>
            Your name:<br>
            <input 
                type="text" 
                name="name"
                style="background-color:white; 
              vertical-align:9px;color: #4F4F4F">
              <br>
              <br>
            Your email addy:<br>
            <input 
                type="text" 
                name="emailaddy"
                style="background-color:white; 
              vertical-align:9px;color: #4F4F4F">
            <br>
            <br>
            Message:<br>
     
            <textarea 
            style="background-color:white; 
              vertical-align:9px;color: #4F4F4F;opacity: 0.3"
            name="message"
            
            ></textarea>
            <br>
            
            </form> 
          
            <br>
            
            <div class="text-normal__grey">
            <button class="btn-ghost__medium text-normal__grey" type="submit" form="form1" value="Submit">Submit</button>
            </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        

          <!-- Google result text-->
        <title>Haseeb Chaudhary creative developer</title>
        <!-- Google result description-->
        <meta name="description" content="I build Web Applications, creatively">

        <!--<meta property="og:title" content="Le Wagon - The French innovative coding school">
        <meta property="og:image" content="facebook-card.jpg">
        <meta property="og:description" content="Le Wagon is the best French coding school for entrepreneurs. Checkout by yourself the projects of our students. You will be impressed.">
        <meta property="og:site_name" content="Le Wagon"/>-->

<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

    </head>
  <body>
 
    <div class="container bg-white">
      
        <div class="centerimage"><%= render  "shared/banner-image" %>
        </div>
      
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

app/views/pages/projects.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        

          <!-- Google result text-->
        <title>Haseeb Chaudhary creative developer</title>
        <!-- Google result description-->
        <meta name="description" content="I build Web Applications, creatively">

        <!--<meta property="og:title" content="Le Wagon - The French innovative coding school">
        <meta property="og:image" content="facebook-card.jpg">
        <meta property="og:description" content="Le Wagon is the best French coding school for entrepreneurs. Checkout by yourself the projects of our students. You will be impressed.">
        <meta property="og:site_name" content="Le Wagon"/>-->

<link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
    
    </head>
<body>



<div class="container">
    <div class="card-standard__white text-center__simple">
        <div class="row" id="about-card-container">
            <div class="text-normal__grey--verylarge">
                <p>Projects</p>
            </div>
            <div class="text-normal__greyandmedium18px">
                <p>Just a small selection of creative building projects ...click and explore</p>
                <br>
            </div>
            <div class="col-xs-12 col-lg-4">
              

               <a target="_blank" href= <%=ldnsouth_path %> >



                <div class="card-overlay__standard">
                    <%= image_tag("bohemian_london_south.jpg", class: "object-fit_cover") %>
                    <div class="overlay-text">
                        <h1>"Bohemian Home in London South."</h1>
                        <p>A London Vicorian terrace which has been given some soul back.</p>
                            <div class="team-title">Haseeb Chaudhary - Marpillero
                            </div>
                    </div>
                </div>
                </a>
            </div>
            <div class="col-xs-12 col-lg-4">
                <a target="_blank" href="https://marpillero.herokuapp.com">
                <div class="card-overlay__standard">
                    <%= image_tag("antoni_griera.jpg", class: "object-fit_cover") %>
                    <div class="overlay-text">
                        <h1>"A House of Soul Barcelona, mountains and the sea."</h1>
                        <p>A beautiful house, designed and built from scrath in the mountains overlooking Barcelona.</p>
                            <div class="team-title">Creative. Sustainable. We design homes for layman pioneers.
                            </div>
                    </div>
                </div>
                </a>
            </div>
            <div class="col-xs-12 col-lg-4">
                <a target="_blank" href="https://ceziam.com/articles">
                <div class="card-overlay__standard">
                    <%= image_tag("blog-app2.jpg", class: "object-fit_cover") %>
                    <div class="overlay-text">
                        <h1>"Expand your world and reach the world."</h1>
                        <p>A easy to use and beautiful bloggging coded from scratch.</p>
                            <div class="team-title">Creative and sustainable. We design homes for layman pioneers.
                            </div>
                    </div>
                </div>
                </a>
            </div>
        </div>
    </div>
</div>


</body>
</html>

app/views/shared/_banner-image.html.erb
   <%= image_tag 'HClogo.png', class: "img-fluid" %> 

app/views/shared/_contact-form-minimal.html.erb
  <div class="contact-form" >
    <form id="form" class="topBefore">
        
          <input id="name" type="text" placeholder="NAME">
          <input id="email" type="text" placeholder="E-MAIL">
          <textarea id="message" type="text" placeholder="MESSAGE"></textarea>
          <input id="submit-contact" type="submit" value="GO!">
      
    </form>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<%= form_for @article do |f| %>
 <p>
   <font color="black">Title
     <%= f.label :title %><br>
    <%= f.text_area :title %>
 </p>

  <font color="black">Description</font>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/shared/_navbar-simple.html.erb
<% if user_signed_in?  %>
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "cool_pic.jpg", height: 50 %> 
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    
      
        <!-- Login link (when logged out) -->
        <!-- 
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        -->

      <!-- Once auth fixed then delete all the stuff below -->
      <!-- Links when logged in -->
        <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'About', about_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'Projects', projects_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'Blog', articles_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to "Logout", destroy_user_session_path,:method => 'delete', class: "navbar-wagon-item navbar-erikablog-link" %>


        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <!--<%= image_tag "https://images.unsplash.com/photo-1543458104-7d567484d770?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=55e879ad1f3b096771251f579aaa3b1f&auto=format&fit=crop&w=675&q=80", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>-->
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>

      
    </div>
<% else %>

  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "cool_pic.jpg", height: 50 %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    
      
        <!-- Login link (when logged out) -->
        <!-- 
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        -->

      <!-- Once auth fixed then delete all the stuff below -->
      <!-- Links when logged in -->
        <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'About', about_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'Projects', projects_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to 'Blog', articles_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-erikablog-link" %>
        <%= link_to "Login", new_user_session_url, class: "navbar-wagon-item navbar-erikablog-link" %>
        


        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <!--<%= image_tag "https://images.unsplash.com/photo-1543458104-7d567484d770?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=55e879ad1f3b096771251f579aaa3b1f&auto=format&fit=crop&w=675&q=80", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>-->
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>

      
    </div>

<% end %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-erikablog-dropdown-menu">
        <li><%= link_to 'Home', root_path %></li>
        <li><a href="about">About</a></li>
        <li><a href="blog">Blog</a></li>
        <li><a href="contact">Contact</a></li>
        
           
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>